CREATE TABLE categories (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE user (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  username VARCHAR(255) NOT NULL,
  hashed_password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE article (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  user_id INT UNSIGNED NOT NULL,
  categories_id INT UNSIGNED NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(categories_id) REFERENCES categories(id),
  FOREIGN KEY(user_id) REFERENCES user(id)
);

INSERT INTO categories(name)
VALUES
("Rock"),
("Electro"),
("Jazz"),
("Rap/Hip-Hop"),
("Pop");
